In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../data/cleaned_sales.csv")
data.head()

Unnamed: 0  shop_id  item_id  date_block_num  item_cnt_month  city_label  \
0           0        2       19               0             0.0           0   
1           1        2       27               0             1.0           0   
2           2        2       28               0             0.0           0   
3           3        2       29               0             0.0           0   
4           4        2       32               0             0.0           0   

   item_category_id  main_category_id  sub_category_id  item_cnt_month_lag_1  \
0                40                11                4                   NaN   
1                19                 5               10                   NaN   
2                30                 8               55                   NaN   
3                23                 5               16                   NaN   
4                40                11                4                   NaN   

      ...      shop_month_mean_lag_3  shop_month_mean_lag_6  \
0     ...                        NaN                    NaN   
1     ...                        NaN                    NaN   
2     ...                        NaN                    NaN   
3     ...                        NaN                    NaN   
4     ...                        NaN                    NaN   

   shop_month_mean_lag_12  shop_category_month_mean_lag_1  \
0                     NaN                             NaN   
1                     NaN                             NaN   
2                     NaN                             NaN   
3                     NaN                             NaN   
4                     NaN                             NaN   

   shop_category_month_mean_lag_2  main_category_month_mean_lag_1  \
0                             NaN                             NaN   
1                             NaN                             NaN   
2                             NaN                             NaN   
3                             NaN                             NaN   
4                             NaN                             NaN   

   sub_category_month_mean_lag_1  month  holidays_in_month  moex_value  
0                            NaN      0                  6         NaN  
1                            NaN      0                  6         NaN  
2                            NaN      0                  6         NaN  
3                            NaN      0                  6         NaN  
4                            NaN      0                  6         NaN  

[5 rows x 33 columns]

In [14]:
data["city_label"].unique()

array([ 0,  1,  2,  4,  6,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19,
       20, 21, 22, 24, 25, 26, 28, 29, 30,  3, 27,  5, 23, 14])

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11128004 entries, 0 to 11128003
Data columns (total 33 columns):
Unnamed: 0                        int64
shop_id                           int64
item_id                           int64
date_block_num                    int64
item_cnt_month                    float64
city_label                        int64
item_category_id                  int64
main_category_id                  int64
sub_category_id                   int64
item_cnt_month_lag_1              float64
item_cnt_month_lag_2              float64
item_cnt_month_lag_3              float64
item_cnt_month_lag_4              float64
item_cnt_month_lag_5              float64
item_cnt_month_lag_6              float64
item_cnt_month_lag_12             float64
item_month_mean_lag_1             float64
item_month_mean_lag_2             float64
item_month_mean_lag_3             float64
item_month_mean_lag_6             float64
item_month_mean_lag_12            float64
shop_month_mean_lag

In [17]:
sales_train = pd.read_csv("data/sales_train.csv")
test = pd.read_csv("data/test.csv")

In [18]:
# removing shop id and item id which are not in test
test_shop_ids = test['shop_id'].unique()
test_item_ids = test['item_id'].unique()
# Only shops that exist in test set.
sales_train = sales_train[sales_train['shop_id'].isin(test_shop_ids)]
# Only items that exist in test set.
sales_train = sales_train[sales_train['item_id'].isin(test_item_ids)]

In [19]:
sales_train['date'] = pd.to_datetime(sales_train['date'], format='%d.%m.%Y')
#now we will create a pivot tabel by going so we get our data in desired form 
#we want get total count value of an item over the whole month for a shop 
# That why we made shop_id and item_id our indices and date_block_num our column 
# the value we want is item_cnt_day and used sum as aggregating function 
dataset = sales_train.pivot_table(index = ['shop_id','item_id'],values = ['item_cnt_day'],columns = ['date_block_num'],fill_value = 0,aggfunc='sum')

In [20]:
# lets reset our indices, so that data should be in way we can easily manipulate
dataset.reset_index(inplace = True)

In [21]:
# Now we will merge our pivot table with the test_data because we want to keep the data of items we have
# predict
dataset = pd.merge(test,dataset,on = ['item_id','shop_id'],how = 'left')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/generic.py:3111: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [24]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 214200 entries, 0 to 214199
Data columns (total 37 columns):
ID                    214200 non-null int64
shop_id               214200 non-null int64
item_id               214200 non-null int64
(item_cnt_day, 0)     111404 non-null float64
(item_cnt_day, 1)     111404 non-null float64
(item_cnt_day, 2)     111404 non-null float64
(item_cnt_day, 3)     111404 non-null float64
(item_cnt_day, 4)     111404 non-null float64
(item_cnt_day, 5)     111404 non-null float64
(item_cnt_day, 6)     111404 non-null float64
(item_cnt_day, 7)     111404 non-null float64
(item_cnt_day, 8)     111404 non-null float64
(item_cnt_day, 9)     111404 non-null float64
(item_cnt_day, 10)    111404 non-null float64
(item_cnt_day, 11)    111404 non-null float64
(item_cnt_day, 12)    111404 non-null float64
(item_cnt_day, 13)    111404 non-null float64
(item_cnt_day, 14)    111404 non-null float64
(item_cnt_day, 15)    111404 non-null float64
(item_cnt_day, 16)   

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2920493 entries, 4 to 11128003
Data columns (total 33 columns):
Unnamed: 0                        int64
shop_id                           int64
item_id                           int64
date_block_num                    int64
item_cnt_month                    float64
city_label                        int64
item_category_id                  int64
main_category_id                  int64
sub_category_id                   int64
item_cnt_month_lag_1              float64
item_cnt_month_lag_2              float64
item_cnt_month_lag_3              float64
item_cnt_month_lag_4              float64
item_cnt_month_lag_5              float64
item_cnt_month_lag_6              float64
item_cnt_month_lag_12             float64
item_month_mean_lag_1             float64
item_month_mean_lag_2             float64
item_month_mean_lag_3             float64
item_month_mean_lag_6             float64
item_month_mean_lag_12            float64
shop_month_mean_lag_

In [31]:
data['shop_id', 'item_id', '']

KeyError: ('shop_id', 'item_id', '')

In [74]:
import torch
from torch import nn, optim
import pandas as pd
from torch.utils.data import Dataset, DataLoader
import numpy as np

import gc

lstm_layer = nn.LSTM(input_size=1, hidden_size=64,  num_layers=2, dropout=0.2, batch_first=True)
linear_layer = nn.Linear(64, 1)

In [68]:
input = torch.FloatTensor(np.random.rand(4,33))
input.shape


torch.Size([4, 33])

In [70]:
lstm_out, lstm_hidd = lstm_layer(input.unsqueeze(2))

In [71]:
lstm_out.shape

torch.Size([4, 33, 64])

In [72]:
predictions = linear_layer(lstm_out.contiguous().view(len(input), -1))

RuntimeError: size mismatch, m1: [4 x 2112], m2: [64 x 1] at ../aten/src/TH/generic/THTensorMath.cpp:197

In [135]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        # Set initial hidden and cell states 
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size) 
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)
        
        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))  # out: tensor of shape (batch_size, seq_length, hidden_size)
        
        # Decode the hidden state of the last time step
        out = self.fc(out[:, -1, :])
        return out

In [136]:
lstm = RNN(input_size=1, hidden_size=64, num_layers=2)
print(lstm)

RNN(
  (lstm): LSTM(1, 64, num_layers=2, batch_first=True)
  (fc): Linear(in_features=64, out_features=1, bias=True)
)


In [137]:
seq = torch.FloatTensor(np.random.rand(4, 33))

In [139]:
lstm(seq.unsqueeze(2))

tensor([[-0.0779],
        [-0.0775],
        [-0.0783],
        [-0.0782]], grad_fn=<AddmmBackward>)

In [116]:
print(seq.view(seq.shape[0], seq.shape[1] ,1, -1).shape)

torch.Size([4, 33, 1, 1])


In [142]:
lstm_out = torch.FloatTensor(np.random.rand(4, 1))
city_emb = torch.FloatTensor(np.random.rand(4, 64))
item_cat_emb = torch.FloatTensor(np.random.rand(4, 64))
shop_id_emb = torch.FloatTensor(np.random.rand(4, 64))


torch.cat((lstm_out, city_emb, item_cat_emb, shop_id_emb), 1).shape

torch.Size([4, 193])

In [143]:
submission_pfs = np.array([])

In [147]:
submission_pfs = np.append(submission_pfs, [1,3,4,2])

In [148]:
submission_pfs

array([1., 3., 4., 2., 1., 3., 4., 2.])

In [149]:
 submission_pfs.clip(0,20)

array([1., 3., 4., 2., 1., 3., 4., 2.])

In [150]:
submission_pfs.ravel()

array([1., 3., 4., 2., 1., 3., 4., 2.])